{
 "title": "Dynamics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Wheel Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, flw_speed as FrontLeft, frw_speed as FrontRight, blw_speed as BackLeft, brw_speed as BackRight\r\nFROM dynamics \r\nJOIN packet on packet.packet_id = dynamics.packet_id\r\nWHERE packet.packet_id % 10 = 0\r\nORDER BY dynamics.packet_id DESC \r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "GPS Velocity vs Acceleration vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  packet.time,\r\n  dynamics.f_gps_velocity,\r\n  cent_mass_accel[1] AS x_accel,\r\n  cent_mass_accel[2] AS y_accel\r\n\r\nFROM dynamics\r\n\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nWHERE packet.packet_id % 25 = 0\r\nORDER BY packet.packet_id DESC\r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, f_gps[0] as lat, f_gps[1] as lon \r\n\r\nFROM dynamics \r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nWHERE now() - to_timestamp(packet.time / 1000) < interval '30 seconds'\r\nAND packet.packet_id % 10 = 0\r\n\r\nORDER BY packet.packet_id DESC\r\n\r\nLIMIT 250\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "GPS Heading vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, dynamics.f_gps_heading\r\nFROM dynamics\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nWHERE packet.packet_id % 10 = 0\r\nORDER BY dynamics.packet_id DESC\r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Ride Hight vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  packet.time,\r\n  dynamics.fl_ride_height\r\n\r\nFROM dynamics\r\n\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nWHERE packet.packet_id % 10 = 0\r\nORDER BY packet.packet_id DESC\r\nLIMIT 600"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM (now() - to_timestamp(time / 1000.0))) AS delay\r\nFROM packet \r\nORDER BY packet_id DESC \r\nLIMIT 1"
    }
   ]
  }
 ]
}