{
 "title": "Electronics",
 "time": { "from": "now-60s", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, shutdown_leg1\nFROM diagnostics_low \nJOIN packet ON packet.packet_id = diagnostics_low.packet_id\nWHERE packet.packet_id % 10 = 0\nORDER BY diagnostics_low.packet_id DESC \nLIMIT 500"
    }
   ]
  },
  {
   "title": "Traction Control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\r\ndynamics.f_gps_velocity,\r\n(dynamics.flw_speed + dynamics.frw_speed)/2 AS fw_speed,\r\n(dynamics.blw_speed + dynamics.brw_speed)/2 AS bw_speed,\r\npacket.time\r\n\r\nFROM dynamics \r\nJOIN packet on packet.packet_id = dynamics.packet_id\r\nWHERE packet.packet_id % 10 = 0\r\nORDER BY packet.packet_id DESC\r\nLIMIT 500\r\n"
    }
   ]
  },
  {
   "title": "LV Power Draw vs Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\npacket.time,\r\npack.lv_v * pack.lv_c as lv_power\r\n\r\n\r\nFROM pack\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nWHERE packet.packet_id % 10 = 0\r\n\r\nORDER BY packet.packet_id DESC\r\nLIMIT 500"
    }
   ]
  },
  {
   "title": "LV Battery Power Draw",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nlv_v * lv_c as lv_power\r\n\r\nFROM pack\r\nWHERE pack.packet_id % 10 = 0\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n"
    }
   ]
  }
 ]
}