{
 "title": "High Voltage Battery",
 "time": { "from": "2025-04-19T09:13:20.642Z", "to": "2025-04-19T09:14:34.627Z" },
 "panels": [
  {
   "title": "High Voltage Battery Voltage vs Time ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, pack.hv_pack_v \r\n\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "HV Power vs Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\npacket.time, \r\npack.hv_c * pack.hv_pack_v as hv_pack_power\r\n\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT cells_v \r\nFROM diagnostics_low \r\nWHERE packet_id % 10 = 0\r\nORDER BY packet_id DESC\r\nLIMIT 1;\r\n"
    }
   ]
  }
 ]
}