{
 "title": "Thermals Dashboard",
 "description": "- Battery\n- Cell temps\n- max\n- min\n- average\n- max temp delta\n- these metrics broken down per segment\n- visualization of each segment schematic with cell temps displayed corresponding to segment location\n- ACU\n- ambient temp\n- bus bar temps\n- precharge/discharge resistor temps\n- pack fuse temp?\n- Air / coolant loop\n- PWM / RPM / flowrate for any pumps\n- PWM / RPM for any fans\n- Inlet / outlet temp sense\n- thermal derate status\n- Motor / Inverter\n- PWM / RPM / flowrate for any pumps\n- PWM / RPM for any fans\n- Inlet / outlet temp\n- lamination thermistor\n- Inverter temp\n- thermal derate status\n- these metrics possibly displayed across thermal schematics / diagrams for easier visualization\n- valve states if that’s something designed",
 "time": { "from": "2025-04-19T09:33:01.657Z", "to": "2025-04-19T09:33:07.827Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Ambient Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, thermal.ambient_temp \r\nFROM thermal\r\n\r\nJOIN packet ON packet.packet_id = thermal.packet_id\r\nWHERE thermal.packet_id % 10 = 0\r\nORDER BY packet.packet_id DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Motor Loop Temps",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  motor_loop_motor_temp AS motor,\r\n  motor_loop_inverter_temp AS inverter, \r\n  motor_loop_rad_temp AS radiator\r\nFROM thermal \r\nWHERE packet_id % 10 = 0\r\nORDER BY packet_id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Motor Loop Temps",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  motor_temp AS motor,\r\n  inverter_temp AS inverter, \r\n  batt_loop_batt_temp AS battery,\r\n  batt_loop_rad_temp AS radiator\r\nFROM thermal \r\nWHERE packet_id % 10 = 0\r\nORDER BY packet_id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Cell Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT bus_bar_temp1, bus_bar_temp2, bus_bar_temp3\r\nFROM thermal\r\nWHERE packet_id % 10 = 0 \r\nORDER BY packet_id\r\nDESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, motor_loop_flow_rate\r\n\r\nFROM thermal \r\nJOIN packet ON packet.packet_id = thermal.packet_id\r\nWHERE thermal.packet_id % 10 = 0\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Radiator Fan Speeds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT motor_loop_rad_fan_speed AS radiator_fan, batt_loop_rad_fan_speed AS battery_fan\r\nFROM thermal\r\nWHERE packet_id % 10 = 0\r\nORDER BY packet_id DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Average Cell Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, pack.avg_cell_temp\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id\r\nLIMIT 500"
    }
   ]
  }
 ]
}