// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: angelique.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface AngeliqueSensorData {
  time: number;
  packetId: number;
  dynamics: AngeliqueDynamics | undefined;
  controls: AngeliqueControls | undefined;
  pack: AngeliquePack | undefined;
  diagnostics: AngeliqueDiagnostics | undefined;
  thermal: AngeliqueThermal | undefined;
}

export interface AngeliqueDynamics {
  torqueRequest: number;
  vcuPosition: number[];
  vcuVelocity: number[];
  vcuAccel: number[];
  gps: number[];
  gpsVelocity: number;
  gpsHeading: number;
  body1Accel: number[];
  body2Accel: number[];
  body3Accel: number[];
  flwAccel: number[];
  frwAccel: number[];
  blwAccel: number[];
  brwAccel: number[];
  body1Gyro: number[];
  body2Gyro: number[];
  body3Gyro: number[];
  flwSpeed: number;
  frwSpeed: number;
  blwSpeed: number;
  brwSpeed: number;
  inverterV: number;
  inverterC: number;
  inverterRpm: number;
  inverterTorque: number;
}

export interface AngeliqueControls {
  vcuFlags: Buffer;
  vcuFlagsJson: string;
  apps1V: number;
  apps2V: number;
  bse1V: number;
  bse2V: number;
  sus1V: number;
  sus2V: number;
  steerV: number;
}

export interface AngeliquePack {
  hvPackV: number;
  hvTractiveV: number;
  hvC: number;
  lvV: number;
  lvC: number;
  contactorState: number;
  avgCellV: number;
  avgCellTemp: number;
}

export interface AngeliqueDiagnostics {
  currentErrors: Buffer;
  currentErrorsJson: string;
  latchingFaults: Buffer;
  latchingFaultsJson: string;
  cellsV: number[];
  hvChargeState: number;
  lvChargeState: number;
  odometer: number;
}

export interface AngeliqueThermal {
  cellsTemp: number[];
  ambientTemp: number;
  inverterTemp: number;
  motorTemp: number;
  waterMotorTemp: number;
  waterInverterTemp: number;
  waterRadTemp: number;
  radFanSet: number;
  radFanRpm: number;
  battFanSet: number;
  battFanRpm: number;
  flowRate: number;
}

function createBaseAngeliqueSensorData(): AngeliqueSensorData {
  return {
    time: 0,
    packetId: 0,
    dynamics: undefined,
    controls: undefined,
    pack: undefined,
    diagnostics: undefined,
    thermal: undefined,
  };
}

export const AngeliqueSensorData: MessageFns<AngeliqueSensorData> = {
  encode(message: AngeliqueSensorData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.time !== 0) {
      writer.uint32(8).int64(message.time);
    }
    if (message.packetId !== 0) {
      writer.uint32(16).int64(message.packetId);
    }
    if (message.dynamics !== undefined) {
      AngeliqueDynamics.encode(message.dynamics, writer.uint32(26).fork()).join();
    }
    if (message.controls !== undefined) {
      AngeliqueControls.encode(message.controls, writer.uint32(34).fork()).join();
    }
    if (message.pack !== undefined) {
      AngeliquePack.encode(message.pack, writer.uint32(42).fork()).join();
    }
    if (message.diagnostics !== undefined) {
      AngeliqueDiagnostics.encode(message.diagnostics, writer.uint32(50).fork()).join();
    }
    if (message.thermal !== undefined) {
      AngeliqueThermal.encode(message.thermal, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliqueSensorData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliqueSensorData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.time = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.packetId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dynamics = AngeliqueDynamics.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.controls = AngeliqueControls.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pack = AngeliquePack.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.diagnostics = AngeliqueDiagnostics.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.thermal = AngeliqueThermal.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliqueSensorData {
    return {
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      packetId: isSet(object.packetId) ? globalThis.Number(object.packetId) : 0,
      dynamics: isSet(object.dynamics) ? AngeliqueDynamics.fromJSON(object.dynamics) : undefined,
      controls: isSet(object.controls) ? AngeliqueControls.fromJSON(object.controls) : undefined,
      pack: isSet(object.pack) ? AngeliquePack.fromJSON(object.pack) : undefined,
      diagnostics: isSet(object.diagnostics) ? AngeliqueDiagnostics.fromJSON(object.diagnostics) : undefined,
      thermal: isSet(object.thermal) ? AngeliqueThermal.fromJSON(object.thermal) : undefined,
    };
  },

  toJSON(message: AngeliqueSensorData): unknown {
    const obj: any = {};
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.packetId !== 0) {
      obj.packetId = Math.round(message.packetId);
    }
    if (message.dynamics !== undefined) {
      obj.dynamics = AngeliqueDynamics.toJSON(message.dynamics);
    }
    if (message.controls !== undefined) {
      obj.controls = AngeliqueControls.toJSON(message.controls);
    }
    if (message.pack !== undefined) {
      obj.pack = AngeliquePack.toJSON(message.pack);
    }
    if (message.diagnostics !== undefined) {
      obj.diagnostics = AngeliqueDiagnostics.toJSON(message.diagnostics);
    }
    if (message.thermal !== undefined) {
      obj.thermal = AngeliqueThermal.toJSON(message.thermal);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliqueSensorData>, I>>(base?: I): AngeliqueSensorData {
    return AngeliqueSensorData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliqueSensorData>, I>>(object: I): AngeliqueSensorData {
    const message = createBaseAngeliqueSensorData();
    message.time = object.time ?? 0;
    message.packetId = object.packetId ?? 0;
    message.dynamics = (object.dynamics !== undefined && object.dynamics !== null)
      ? AngeliqueDynamics.fromPartial(object.dynamics)
      : undefined;
    message.controls = (object.controls !== undefined && object.controls !== null)
      ? AngeliqueControls.fromPartial(object.controls)
      : undefined;
    message.pack = (object.pack !== undefined && object.pack !== null)
      ? AngeliquePack.fromPartial(object.pack)
      : undefined;
    message.diagnostics = (object.diagnostics !== undefined && object.diagnostics !== null)
      ? AngeliqueDiagnostics.fromPartial(object.diagnostics)
      : undefined;
    message.thermal = (object.thermal !== undefined && object.thermal !== null)
      ? AngeliqueThermal.fromPartial(object.thermal)
      : undefined;
    return message;
  },
};

function createBaseAngeliqueDynamics(): AngeliqueDynamics {
  return {
    torqueRequest: 0,
    vcuPosition: [],
    vcuVelocity: [],
    vcuAccel: [],
    gps: [],
    gpsVelocity: 0,
    gpsHeading: 0,
    body1Accel: [],
    body2Accel: [],
    body3Accel: [],
    flwAccel: [],
    frwAccel: [],
    blwAccel: [],
    brwAccel: [],
    body1Gyro: [],
    body2Gyro: [],
    body3Gyro: [],
    flwSpeed: 0,
    frwSpeed: 0,
    blwSpeed: 0,
    brwSpeed: 0,
    inverterV: 0,
    inverterC: 0,
    inverterRpm: 0,
    inverterTorque: 0,
  };
}

export const AngeliqueDynamics: MessageFns<AngeliqueDynamics> = {
  encode(message: AngeliqueDynamics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.torqueRequest !== 0) {
      writer.uint32(69).float(message.torqueRequest);
    }
    writer.uint32(74).fork();
    for (const v of message.vcuPosition) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(82).fork();
    for (const v of message.vcuVelocity) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(90).fork();
    for (const v of message.vcuAccel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(98).fork();
    for (const v of message.gps) {
      writer.float(v);
    }
    writer.join();
    if (message.gpsVelocity !== 0) {
      writer.uint32(109).float(message.gpsVelocity);
    }
    if (message.gpsHeading !== 0) {
      writer.uint32(117).float(message.gpsHeading);
    }
    writer.uint32(122).fork();
    for (const v of message.body1Accel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(130).fork();
    for (const v of message.body2Accel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(138).fork();
    for (const v of message.body3Accel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(146).fork();
    for (const v of message.flwAccel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(154).fork();
    for (const v of message.frwAccel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(162).fork();
    for (const v of message.blwAccel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(170).fork();
    for (const v of message.brwAccel) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(178).fork();
    for (const v of message.body1Gyro) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(186).fork();
    for (const v of message.body2Gyro) {
      writer.float(v);
    }
    writer.join();
    writer.uint32(194).fork();
    for (const v of message.body3Gyro) {
      writer.float(v);
    }
    writer.join();
    if (message.flwSpeed !== 0) {
      writer.uint32(205).float(message.flwSpeed);
    }
    if (message.frwSpeed !== 0) {
      writer.uint32(213).float(message.frwSpeed);
    }
    if (message.blwSpeed !== 0) {
      writer.uint32(221).float(message.blwSpeed);
    }
    if (message.brwSpeed !== 0) {
      writer.uint32(229).float(message.brwSpeed);
    }
    if (message.inverterV !== 0) {
      writer.uint32(237).float(message.inverterV);
    }
    if (message.inverterC !== 0) {
      writer.uint32(245).float(message.inverterC);
    }
    if (message.inverterRpm !== 0) {
      writer.uint32(248).int32(message.inverterRpm);
    }
    if (message.inverterTorque !== 0) {
      writer.uint32(261).float(message.inverterTorque);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliqueDynamics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliqueDynamics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.torqueRequest = reader.float();
          continue;
        }
        case 9: {
          if (tag === 77) {
            message.vcuPosition.push(reader.float());

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.vcuPosition.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 10: {
          if (tag === 85) {
            message.vcuVelocity.push(reader.float());

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.vcuVelocity.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 11: {
          if (tag === 93) {
            message.vcuAccel.push(reader.float());

            continue;
          }

          if (tag === 90) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.vcuAccel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 12: {
          if (tag === 101) {
            message.gps.push(reader.float());

            continue;
          }

          if (tag === 98) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.gps.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 13: {
          if (tag !== 109) {
            break;
          }

          message.gpsVelocity = reader.float();
          continue;
        }
        case 14: {
          if (tag !== 117) {
            break;
          }

          message.gpsHeading = reader.float();
          continue;
        }
        case 15: {
          if (tag === 125) {
            message.body1Accel.push(reader.float());

            continue;
          }

          if (tag === 122) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body1Accel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 16: {
          if (tag === 133) {
            message.body2Accel.push(reader.float());

            continue;
          }

          if (tag === 130) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body2Accel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 17: {
          if (tag === 141) {
            message.body3Accel.push(reader.float());

            continue;
          }

          if (tag === 138) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body3Accel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 18: {
          if (tag === 149) {
            message.flwAccel.push(reader.float());

            continue;
          }

          if (tag === 146) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.flwAccel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 19: {
          if (tag === 157) {
            message.frwAccel.push(reader.float());

            continue;
          }

          if (tag === 154) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.frwAccel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 20: {
          if (tag === 165) {
            message.blwAccel.push(reader.float());

            continue;
          }

          if (tag === 162) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.blwAccel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 21: {
          if (tag === 173) {
            message.brwAccel.push(reader.float());

            continue;
          }

          if (tag === 170) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.brwAccel.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 22: {
          if (tag === 181) {
            message.body1Gyro.push(reader.float());

            continue;
          }

          if (tag === 178) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body1Gyro.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 23: {
          if (tag === 189) {
            message.body2Gyro.push(reader.float());

            continue;
          }

          if (tag === 186) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body2Gyro.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 24: {
          if (tag === 197) {
            message.body3Gyro.push(reader.float());

            continue;
          }

          if (tag === 194) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.body3Gyro.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 25: {
          if (tag !== 205) {
            break;
          }

          message.flwSpeed = reader.float();
          continue;
        }
        case 26: {
          if (tag !== 213) {
            break;
          }

          message.frwSpeed = reader.float();
          continue;
        }
        case 27: {
          if (tag !== 221) {
            break;
          }

          message.blwSpeed = reader.float();
          continue;
        }
        case 28: {
          if (tag !== 229) {
            break;
          }

          message.brwSpeed = reader.float();
          continue;
        }
        case 29: {
          if (tag !== 237) {
            break;
          }

          message.inverterV = reader.float();
          continue;
        }
        case 30: {
          if (tag !== 245) {
            break;
          }

          message.inverterC = reader.float();
          continue;
        }
        case 31: {
          if (tag !== 248) {
            break;
          }

          message.inverterRpm = reader.int32();
          continue;
        }
        case 32: {
          if (tag !== 261) {
            break;
          }

          message.inverterTorque = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliqueDynamics {
    return {
      torqueRequest: isSet(object.torqueRequest) ? globalThis.Number(object.torqueRequest) : 0,
      vcuPosition: globalThis.Array.isArray(object?.vcuPosition)
        ? object.vcuPosition.map((e: any) => globalThis.Number(e))
        : [],
      vcuVelocity: globalThis.Array.isArray(object?.vcuVelocity)
        ? object.vcuVelocity.map((e: any) => globalThis.Number(e))
        : [],
      vcuAccel: globalThis.Array.isArray(object?.vcuAccel) ? object.vcuAccel.map((e: any) => globalThis.Number(e)) : [],
      gps: globalThis.Array.isArray(object?.gps) ? object.gps.map((e: any) => globalThis.Number(e)) : [],
      gpsVelocity: isSet(object.gpsVelocity) ? globalThis.Number(object.gpsVelocity) : 0,
      gpsHeading: isSet(object.gpsHeading) ? globalThis.Number(object.gpsHeading) : 0,
      body1Accel: globalThis.Array.isArray(object?.body1Accel)
        ? object.body1Accel.map((e: any) => globalThis.Number(e))
        : [],
      body2Accel: globalThis.Array.isArray(object?.body2Accel)
        ? object.body2Accel.map((e: any) => globalThis.Number(e))
        : [],
      body3Accel: globalThis.Array.isArray(object?.body3Accel)
        ? object.body3Accel.map((e: any) => globalThis.Number(e))
        : [],
      flwAccel: globalThis.Array.isArray(object?.flwAccel)
        ? object.flwAccel.map((e: any) => globalThis.Number(e))
        : [],
      frwAccel: globalThis.Array.isArray(object?.frwAccel) ? object.frwAccel.map((e: any) => globalThis.Number(e)) : [],
      blwAccel: globalThis.Array.isArray(object?.blwAccel) ? object.blwAccel.map((e: any) => globalThis.Number(e)) : [],
      brwAccel: globalThis.Array.isArray(object?.brwAccel) ? object.brwAccel.map((e: any) => globalThis.Number(e)) : [],
      body1Gyro: globalThis.Array.isArray(object?.body1Gyro)
        ? object.body1Gyro.map((e: any) => globalThis.Number(e))
        : [],
      body2Gyro: globalThis.Array.isArray(object?.body2Gyro)
        ? object.body2Gyro.map((e: any) => globalThis.Number(e))
        : [],
      body3Gyro: globalThis.Array.isArray(object?.body3Gyro)
        ? object.body3Gyro.map((e: any) => globalThis.Number(e))
        : [],
      flwSpeed: isSet(object.flwSpeed) ? globalThis.Number(object.flwSpeed) : 0,
      frwSpeed: isSet(object.frwSpeed) ? globalThis.Number(object.frwSpeed) : 0,
      blwSpeed: isSet(object.blwSpeed) ? globalThis.Number(object.blwSpeed) : 0,
      brwSpeed: isSet(object.brwSpeed) ? globalThis.Number(object.brwSpeed) : 0,
      inverterV: isSet(object.inverterV) ? globalThis.Number(object.inverterV) : 0,
      inverterC: isSet(object.inverterC) ? globalThis.Number(object.inverterC) : 0,
      inverterRpm: isSet(object.inverterRpm) ? globalThis.Number(object.inverterRpm) : 0,
      inverterTorque: isSet(object.inverterTorque) ? globalThis.Number(object.inverterTorque) : 0,
    };
  },

  toJSON(message: AngeliqueDynamics): unknown {
    const obj: any = {};
    if (message.torqueRequest !== 0) {
      obj.torqueRequest = message.torqueRequest;
    }
    if (message.vcuPosition?.length) {
      obj.vcuPosition = message.vcuPosition;
    }
    if (message.vcuVelocity?.length) {
      obj.vcuVelocity = message.vcuVelocity;
    }
    if (message.vcuAccel?.length) {
      obj.vcuAccel = message.vcuAccel;
    }
    if (message.gps?.length) {
      obj.gps = message.gps;
    }
    if (message.gpsVelocity !== 0) {
      obj.gpsVelocity = message.gpsVelocity;
    }
    if (message.gpsHeading !== 0) {
      obj.gpsHeading = message.gpsHeading;
    }
    if (message.body1Accel?.length) {
      obj.body1Accel = message.body1Accel;
    }
    if (message.body2Accel?.length) {
      obj.body2Accel = message.body2Accel;
    }
    if (message.body3Accel?.length) {
      obj.body3Accel = message.body3Accel;
    }
    if (message.flwAccel?.length) {
      obj.flwAccel = message.flwAccel;
    }
    if (message.frwAccel?.length) {
      obj.frwAccel = message.frwAccel;
    }
    if (message.blwAccel?.length) {
      obj.blwAccel = message.blwAccel;
    }
    if (message.brwAccel?.length) {
      obj.brwAccel = message.brwAccel;
    }
    if (message.body1Gyro?.length) {
      obj.body1Gyro = message.body1Gyro;
    }
    if (message.body2Gyro?.length) {
      obj.body2Gyro = message.body2Gyro;
    }
    if (message.body3Gyro?.length) {
      obj.body3Gyro = message.body3Gyro;
    }
    if (message.flwSpeed !== 0) {
      obj.flwSpeed = message.flwSpeed;
    }
    if (message.frwSpeed !== 0) {
      obj.frwSpeed = message.frwSpeed;
    }
    if (message.blwSpeed !== 0) {
      obj.blwSpeed = message.blwSpeed;
    }
    if (message.brwSpeed !== 0) {
      obj.brwSpeed = message.brwSpeed;
    }
    if (message.inverterV !== 0) {
      obj.inverterV = message.inverterV;
    }
    if (message.inverterC !== 0) {
      obj.inverterC = message.inverterC;
    }
    if (message.inverterRpm !== 0) {
      obj.inverterRpm = Math.round(message.inverterRpm);
    }
    if (message.inverterTorque !== 0) {
      obj.inverterTorque = message.inverterTorque;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliqueDynamics>, I>>(base?: I): AngeliqueDynamics {
    return AngeliqueDynamics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliqueDynamics>, I>>(object: I): AngeliqueDynamics {
    const message = createBaseAngeliqueDynamics();
    message.torqueRequest = object.torqueRequest ?? 0;
    message.vcuPosition = object.vcuPosition?.map((e) => e) || [];
    message.vcuVelocity = object.vcuVelocity?.map((e) => e) || [];
    message.vcuAccel = object.vcuAccel?.map((e) => e) || [];
    message.gps = object.gps?.map((e) => e) || [];
    message.gpsVelocity = object.gpsVelocity ?? 0;
    message.gpsHeading = object.gpsHeading ?? 0;
    message.body1Accel = object.body1Accel?.map((e) => e) || [];
    message.body2Accel = object.body2Accel?.map((e) => e) || [];
    message.body3Accel = object.body3Accel?.map((e) => e) || [];
    message.flwAccel = object.flwAccel?.map((e) => e) || [];
    message.frwAccel = object.frwAccel?.map((e) => e) || [];
    message.blwAccel = object.blwAccel?.map((e) => e) || [];
    message.brwAccel = object.brwAccel?.map((e) => e) || [];
    message.body1Gyro = object.body1Gyro?.map((e) => e) || [];
    message.body2Gyro = object.body2Gyro?.map((e) => e) || [];
    message.body3Gyro = object.body3Gyro?.map((e) => e) || [];
    message.flwSpeed = object.flwSpeed ?? 0;
    message.frwSpeed = object.frwSpeed ?? 0;
    message.blwSpeed = object.blwSpeed ?? 0;
    message.brwSpeed = object.brwSpeed ?? 0;
    message.inverterV = object.inverterV ?? 0;
    message.inverterC = object.inverterC ?? 0;
    message.inverterRpm = object.inverterRpm ?? 0;
    message.inverterTorque = object.inverterTorque ?? 0;
    return message;
  },
};

function createBaseAngeliqueControls(): AngeliqueControls {
  return {
    vcuFlags: Buffer.alloc(0),
    vcuFlagsJson: "",
    apps1V: 0,
    apps2V: 0,
    bse1V: 0,
    bse2V: 0,
    sus1V: 0,
    sus2V: 0,
    steerV: 0,
  };
}

export const AngeliqueControls: MessageFns<AngeliqueControls> = {
  encode(message: AngeliqueControls, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vcuFlags.length !== 0) {
      writer.uint32(266).bytes(message.vcuFlags);
    }
    if (message.vcuFlagsJson !== "") {
      writer.uint32(274).string(message.vcuFlagsJson);
    }
    if (message.apps1V !== 0) {
      writer.uint32(285).float(message.apps1V);
    }
    if (message.apps2V !== 0) {
      writer.uint32(293).float(message.apps2V);
    }
    if (message.bse1V !== 0) {
      writer.uint32(301).float(message.bse1V);
    }
    if (message.bse2V !== 0) {
      writer.uint32(309).float(message.bse2V);
    }
    if (message.sus1V !== 0) {
      writer.uint32(317).float(message.sus1V);
    }
    if (message.sus2V !== 0) {
      writer.uint32(325).float(message.sus2V);
    }
    if (message.steerV !== 0) {
      writer.uint32(333).float(message.steerV);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliqueControls {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliqueControls();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 33: {
          if (tag !== 266) {
            break;
          }

          message.vcuFlags = Buffer.from(reader.bytes());
          continue;
        }
        case 34: {
          if (tag !== 274) {
            break;
          }

          message.vcuFlagsJson = reader.string();
          continue;
        }
        case 35: {
          if (tag !== 285) {
            break;
          }

          message.apps1V = reader.float();
          continue;
        }
        case 36: {
          if (tag !== 293) {
            break;
          }

          message.apps2V = reader.float();
          continue;
        }
        case 37: {
          if (tag !== 301) {
            break;
          }

          message.bse1V = reader.float();
          continue;
        }
        case 38: {
          if (tag !== 309) {
            break;
          }

          message.bse2V = reader.float();
          continue;
        }
        case 39: {
          if (tag !== 317) {
            break;
          }

          message.sus1V = reader.float();
          continue;
        }
        case 40: {
          if (tag !== 325) {
            break;
          }

          message.sus2V = reader.float();
          continue;
        }
        case 41: {
          if (tag !== 333) {
            break;
          }

          message.steerV = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliqueControls {
    return {
      vcuFlags: isSet(object.vcuFlags) ? Buffer.from(bytesFromBase64(object.vcuFlags)) : Buffer.alloc(0),
      vcuFlagsJson: isSet(object.vcuFlagsJson) ? globalThis.String(object.vcuFlagsJson) : "",
      apps1V: isSet(object.apps1V) ? globalThis.Number(object.apps1V) : 0,
      apps2V: isSet(object.apps2V) ? globalThis.Number(object.apps2V) : 0,
      bse1V: isSet(object.bse1V) ? globalThis.Number(object.bse1V) : 0,
      bse2V: isSet(object.bse2V) ? globalThis.Number(object.bse2V) : 0,
      sus1V: isSet(object.sus1V) ? globalThis.Number(object.sus1V) : 0,
      sus2V: isSet(object.sus2V) ? globalThis.Number(object.sus2V) : 0,
      steerV: isSet(object.steerV) ? globalThis.Number(object.steerV) : 0,
    };
  },

  toJSON(message: AngeliqueControls): unknown {
    const obj: any = {};
    if (message.vcuFlags.length !== 0) {
      obj.vcuFlags = base64FromBytes(message.vcuFlags);
    }
    if (message.vcuFlagsJson !== "") {
      obj.vcuFlagsJson = message.vcuFlagsJson;
    }
    if (message.apps1V !== 0) {
      obj.apps1V = message.apps1V;
    }
    if (message.apps2V !== 0) {
      obj.apps2V = message.apps2V;
    }
    if (message.bse1V !== 0) {
      obj.bse1V = message.bse1V;
    }
    if (message.bse2V !== 0) {
      obj.bse2V = message.bse2V;
    }
    if (message.sus1V !== 0) {
      obj.sus1V = message.sus1V;
    }
    if (message.sus2V !== 0) {
      obj.sus2V = message.sus2V;
    }
    if (message.steerV !== 0) {
      obj.steerV = message.steerV;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliqueControls>, I>>(base?: I): AngeliqueControls {
    return AngeliqueControls.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliqueControls>, I>>(object: I): AngeliqueControls {
    const message = createBaseAngeliqueControls();
    message.vcuFlags = object.vcuFlags ?? Buffer.alloc(0);
    message.vcuFlagsJson = object.vcuFlagsJson ?? "";
    message.apps1V = object.apps1V ?? 0;
    message.apps2V = object.apps2V ?? 0;
    message.bse1V = object.bse1V ?? 0;
    message.bse2V = object.bse2V ?? 0;
    message.sus1V = object.sus1V ?? 0;
    message.sus2V = object.sus2V ?? 0;
    message.steerV = object.steerV ?? 0;
    return message;
  },
};

function createBaseAngeliquePack(): AngeliquePack {
  return { hvPackV: 0, hvTractiveV: 0, hvC: 0, lvV: 0, lvC: 0, contactorState: 0, avgCellV: 0, avgCellTemp: 0 };
}

export const AngeliquePack: MessageFns<AngeliquePack> = {
  encode(message: AngeliquePack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hvPackV !== 0) {
      writer.uint32(341).float(message.hvPackV);
    }
    if (message.hvTractiveV !== 0) {
      writer.uint32(349).float(message.hvTractiveV);
    }
    if (message.hvC !== 0) {
      writer.uint32(357).float(message.hvC);
    }
    if (message.lvV !== 0) {
      writer.uint32(365).float(message.lvV);
    }
    if (message.lvC !== 0) {
      writer.uint32(373).float(message.lvC);
    }
    if (message.contactorState !== 0) {
      writer.uint32(376).int32(message.contactorState);
    }
    if (message.avgCellV !== 0) {
      writer.uint32(389).float(message.avgCellV);
    }
    if (message.avgCellTemp !== 0) {
      writer.uint32(397).float(message.avgCellTemp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliquePack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliquePack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 42: {
          if (tag !== 341) {
            break;
          }

          message.hvPackV = reader.float();
          continue;
        }
        case 43: {
          if (tag !== 349) {
            break;
          }

          message.hvTractiveV = reader.float();
          continue;
        }
        case 44: {
          if (tag !== 357) {
            break;
          }

          message.hvC = reader.float();
          continue;
        }
        case 45: {
          if (tag !== 365) {
            break;
          }

          message.lvV = reader.float();
          continue;
        }
        case 46: {
          if (tag !== 373) {
            break;
          }

          message.lvC = reader.float();
          continue;
        }
        case 47: {
          if (tag !== 376) {
            break;
          }

          message.contactorState = reader.int32();
          continue;
        }
        case 48: {
          if (tag !== 389) {
            break;
          }

          message.avgCellV = reader.float();
          continue;
        }
        case 49: {
          if (tag !== 397) {
            break;
          }

          message.avgCellTemp = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliquePack {
    return {
      hvPackV: isSet(object.hvPackV) ? globalThis.Number(object.hvPackV) : 0,
      hvTractiveV: isSet(object.hvTractiveV) ? globalThis.Number(object.hvTractiveV) : 0,
      hvC: isSet(object.hvC) ? globalThis.Number(object.hvC) : 0,
      lvV: isSet(object.lvV) ? globalThis.Number(object.lvV) : 0,
      lvC: isSet(object.lvC) ? globalThis.Number(object.lvC) : 0,
      contactorState: isSet(object.contactorState) ? globalThis.Number(object.contactorState) : 0,
      avgCellV: isSet(object.avgCellV) ? globalThis.Number(object.avgCellV) : 0,
      avgCellTemp: isSet(object.avgCellTemp) ? globalThis.Number(object.avgCellTemp) : 0,
    };
  },

  toJSON(message: AngeliquePack): unknown {
    const obj: any = {};
    if (message.hvPackV !== 0) {
      obj.hvPackV = message.hvPackV;
    }
    if (message.hvTractiveV !== 0) {
      obj.hvTractiveV = message.hvTractiveV;
    }
    if (message.hvC !== 0) {
      obj.hvC = message.hvC;
    }
    if (message.lvV !== 0) {
      obj.lvV = message.lvV;
    }
    if (message.lvC !== 0) {
      obj.lvC = message.lvC;
    }
    if (message.contactorState !== 0) {
      obj.contactorState = Math.round(message.contactorState);
    }
    if (message.avgCellV !== 0) {
      obj.avgCellV = message.avgCellV;
    }
    if (message.avgCellTemp !== 0) {
      obj.avgCellTemp = message.avgCellTemp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliquePack>, I>>(base?: I): AngeliquePack {
    return AngeliquePack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliquePack>, I>>(object: I): AngeliquePack {
    const message = createBaseAngeliquePack();
    message.hvPackV = object.hvPackV ?? 0;
    message.hvTractiveV = object.hvTractiveV ?? 0;
    message.hvC = object.hvC ?? 0;
    message.lvV = object.lvV ?? 0;
    message.lvC = object.lvC ?? 0;
    message.contactorState = object.contactorState ?? 0;
    message.avgCellV = object.avgCellV ?? 0;
    message.avgCellTemp = object.avgCellTemp ?? 0;
    return message;
  },
};

function createBaseAngeliqueDiagnostics(): AngeliqueDiagnostics {
  return {
    currentErrors: Buffer.alloc(0),
    currentErrorsJson: "",
    latchingFaults: Buffer.alloc(0),
    latchingFaultsJson: "",
    cellsV: [],
    hvChargeState: 0,
    lvChargeState: 0,
    odometer: 0,
  };
}

export const AngeliqueDiagnostics: MessageFns<AngeliqueDiagnostics> = {
  encode(message: AngeliqueDiagnostics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentErrors.length !== 0) {
      writer.uint32(402).bytes(message.currentErrors);
    }
    if (message.currentErrorsJson !== "") {
      writer.uint32(410).string(message.currentErrorsJson);
    }
    if (message.latchingFaults.length !== 0) {
      writer.uint32(418).bytes(message.latchingFaults);
    }
    if (message.latchingFaultsJson !== "") {
      writer.uint32(426).string(message.latchingFaultsJson);
    }
    writer.uint32(434).fork();
    for (const v of message.cellsV) {
      writer.float(v);
    }
    writer.join();
    if (message.hvChargeState !== 0) {
      writer.uint32(445).float(message.hvChargeState);
    }
    if (message.lvChargeState !== 0) {
      writer.uint32(453).float(message.lvChargeState);
    }
    if (message.odometer !== 0) {
      writer.uint32(461).float(message.odometer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliqueDiagnostics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliqueDiagnostics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 50: {
          if (tag !== 402) {
            break;
          }

          message.currentErrors = Buffer.from(reader.bytes());
          continue;
        }
        case 51: {
          if (tag !== 410) {
            break;
          }

          message.currentErrorsJson = reader.string();
          continue;
        }
        case 52: {
          if (tag !== 418) {
            break;
          }

          message.latchingFaults = Buffer.from(reader.bytes());
          continue;
        }
        case 53: {
          if (tag !== 426) {
            break;
          }

          message.latchingFaultsJson = reader.string();
          continue;
        }
        case 54: {
          if (tag === 437) {
            message.cellsV.push(reader.float());

            continue;
          }

          if (tag === 434) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.cellsV.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 55: {
          if (tag !== 445) {
            break;
          }

          message.hvChargeState = reader.float();
          continue;
        }
        case 56: {
          if (tag !== 453) {
            break;
          }

          message.lvChargeState = reader.float();
          continue;
        }
        case 57: {
          if (tag !== 461) {
            break;
          }

          message.odometer = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliqueDiagnostics {
    return {
      currentErrors: isSet(object.currentErrors) ? Buffer.from(bytesFromBase64(object.currentErrors)) : Buffer.alloc(0),
      currentErrorsJson: isSet(object.currentErrorsJson) ? globalThis.String(object.currentErrorsJson) : "",
      latchingFaults: isSet(object.latchingFaults)
        ? Buffer.from(bytesFromBase64(object.latchingFaults))
        : Buffer.alloc(0),
      latchingFaultsJson: isSet(object.latchingFaultsJson) ? globalThis.String(object.latchingFaultsJson) : "",
      cellsV: globalThis.Array.isArray(object?.cellsV) ? object.cellsV.map((e: any) => globalThis.Number(e)) : [],
      hvChargeState: isSet(object.hvChargeState) ? globalThis.Number(object.hvChargeState) : 0,
      lvChargeState: isSet(object.lvChargeState) ? globalThis.Number(object.lvChargeState) : 0,
      odometer: isSet(object.odometer) ? globalThis.Number(object.odometer) : 0,
    };
  },

  toJSON(message: AngeliqueDiagnostics): unknown {
    const obj: any = {};
    if (message.currentErrors.length !== 0) {
      obj.currentErrors = base64FromBytes(message.currentErrors);
    }
    if (message.currentErrorsJson !== "") {
      obj.currentErrorsJson = message.currentErrorsJson;
    }
    if (message.latchingFaults.length !== 0) {
      obj.latchingFaults = base64FromBytes(message.latchingFaults);
    }
    if (message.latchingFaultsJson !== "") {
      obj.latchingFaultsJson = message.latchingFaultsJson;
    }
    if (message.cellsV?.length) {
      obj.cellsV = message.cellsV;
    }
    if (message.hvChargeState !== 0) {
      obj.hvChargeState = message.hvChargeState;
    }
    if (message.lvChargeState !== 0) {
      obj.lvChargeState = message.lvChargeState;
    }
    if (message.odometer !== 0) {
      obj.odometer = message.odometer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliqueDiagnostics>, I>>(base?: I): AngeliqueDiagnostics {
    return AngeliqueDiagnostics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliqueDiagnostics>, I>>(object: I): AngeliqueDiagnostics {
    const message = createBaseAngeliqueDiagnostics();
    message.currentErrors = object.currentErrors ?? Buffer.alloc(0);
    message.currentErrorsJson = object.currentErrorsJson ?? "";
    message.latchingFaults = object.latchingFaults ?? Buffer.alloc(0);
    message.latchingFaultsJson = object.latchingFaultsJson ?? "";
    message.cellsV = object.cellsV?.map((e) => e) || [];
    message.hvChargeState = object.hvChargeState ?? 0;
    message.lvChargeState = object.lvChargeState ?? 0;
    message.odometer = object.odometer ?? 0;
    return message;
  },
};

function createBaseAngeliqueThermal(): AngeliqueThermal {
  return {
    cellsTemp: [],
    ambientTemp: 0,
    inverterTemp: 0,
    motorTemp: 0,
    waterMotorTemp: 0,
    waterInverterTemp: 0,
    waterRadTemp: 0,
    radFanSet: 0,
    radFanRpm: 0,
    battFanSet: 0,
    battFanRpm: 0,
    flowRate: 0,
  };
}

export const AngeliqueThermal: MessageFns<AngeliqueThermal> = {
  encode(message: AngeliqueThermal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(466).fork();
    for (const v of message.cellsTemp) {
      writer.int32(v);
    }
    writer.join();
    if (message.ambientTemp !== 0) {
      writer.uint32(472).int32(message.ambientTemp);
    }
    if (message.inverterTemp !== 0) {
      writer.uint32(480).int32(message.inverterTemp);
    }
    if (message.motorTemp !== 0) {
      writer.uint32(488).int32(message.motorTemp);
    }
    if (message.waterMotorTemp !== 0) {
      writer.uint32(496).int32(message.waterMotorTemp);
    }
    if (message.waterInverterTemp !== 0) {
      writer.uint32(504).int32(message.waterInverterTemp);
    }
    if (message.waterRadTemp !== 0) {
      writer.uint32(512).int32(message.waterRadTemp);
    }
    if (message.radFanSet !== 0) {
      writer.uint32(520).int32(message.radFanSet);
    }
    if (message.radFanRpm !== 0) {
      writer.uint32(528).int64(message.radFanRpm);
    }
    if (message.battFanSet !== 0) {
      writer.uint32(536).int32(message.battFanSet);
    }
    if (message.battFanRpm !== 0) {
      writer.uint32(544).int32(message.battFanRpm);
    }
    if (message.flowRate !== 0) {
      writer.uint32(552).int32(message.flowRate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AngeliqueThermal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAngeliqueThermal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 58: {
          if (tag === 464) {
            message.cellsTemp.push(reader.int32());

            continue;
          }

          if (tag === 466) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.cellsTemp.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 59: {
          if (tag !== 472) {
            break;
          }

          message.ambientTemp = reader.int32();
          continue;
        }
        case 60: {
          if (tag !== 480) {
            break;
          }

          message.inverterTemp = reader.int32();
          continue;
        }
        case 61: {
          if (tag !== 488) {
            break;
          }

          message.motorTemp = reader.int32();
          continue;
        }
        case 62: {
          if (tag !== 496) {
            break;
          }

          message.waterMotorTemp = reader.int32();
          continue;
        }
        case 63: {
          if (tag !== 504) {
            break;
          }

          message.waterInverterTemp = reader.int32();
          continue;
        }
        case 64: {
          if (tag !== 512) {
            break;
          }

          message.waterRadTemp = reader.int32();
          continue;
        }
        case 65: {
          if (tag !== 520) {
            break;
          }

          message.radFanSet = reader.int32();
          continue;
        }
        case 66: {
          if (tag !== 528) {
            break;
          }

          message.radFanRpm = longToNumber(reader.int64());
          continue;
        }
        case 67: {
          if (tag !== 536) {
            break;
          }

          message.battFanSet = reader.int32();
          continue;
        }
        case 68: {
          if (tag !== 544) {
            break;
          }

          message.battFanRpm = reader.int32();
          continue;
        }
        case 69: {
          if (tag !== 552) {
            break;
          }

          message.flowRate = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AngeliqueThermal {
    return {
      cellsTemp: globalThis.Array.isArray(object?.cellsTemp)
        ? object.cellsTemp.map((e: any) => globalThis.Number(e))
        : [],
      ambientTemp: isSet(object.ambientTemp) ? globalThis.Number(object.ambientTemp) : 0,
      inverterTemp: isSet(object.inverterTemp) ? globalThis.Number(object.inverterTemp) : 0,
      motorTemp: isSet(object.motorTemp) ? globalThis.Number(object.motorTemp) : 0,
      waterMotorTemp: isSet(object.waterMotorTemp) ? globalThis.Number(object.waterMotorTemp) : 0,
      waterInverterTemp: isSet(object.waterInverterTemp) ? globalThis.Number(object.waterInverterTemp) : 0,
      waterRadTemp: isSet(object.waterRadTemp) ? globalThis.Number(object.waterRadTemp) : 0,
      radFanSet: isSet(object.radFanSet) ? globalThis.Number(object.radFanSet) : 0,
      radFanRpm: isSet(object.radFanRpm) ? globalThis.Number(object.radFanRpm) : 0,
      battFanSet: isSet(object.battFanSet) ? globalThis.Number(object.battFanSet) : 0,
      battFanRpm: isSet(object.battFanRpm) ? globalThis.Number(object.battFanRpm) : 0,
      flowRate: isSet(object.flowRate) ? globalThis.Number(object.flowRate) : 0,
    };
  },

  toJSON(message: AngeliqueThermal): unknown {
    const obj: any = {};
    if (message.cellsTemp?.length) {
      obj.cellsTemp = message.cellsTemp.map((e) => Math.round(e));
    }
    if (message.ambientTemp !== 0) {
      obj.ambientTemp = Math.round(message.ambientTemp);
    }
    if (message.inverterTemp !== 0) {
      obj.inverterTemp = Math.round(message.inverterTemp);
    }
    if (message.motorTemp !== 0) {
      obj.motorTemp = Math.round(message.motorTemp);
    }
    if (message.waterMotorTemp !== 0) {
      obj.waterMotorTemp = Math.round(message.waterMotorTemp);
    }
    if (message.waterInverterTemp !== 0) {
      obj.waterInverterTemp = Math.round(message.waterInverterTemp);
    }
    if (message.waterRadTemp !== 0) {
      obj.waterRadTemp = Math.round(message.waterRadTemp);
    }
    if (message.radFanSet !== 0) {
      obj.radFanSet = Math.round(message.radFanSet);
    }
    if (message.radFanRpm !== 0) {
      obj.radFanRpm = Math.round(message.radFanRpm);
    }
    if (message.battFanSet !== 0) {
      obj.battFanSet = Math.round(message.battFanSet);
    }
    if (message.battFanRpm !== 0) {
      obj.battFanRpm = Math.round(message.battFanRpm);
    }
    if (message.flowRate !== 0) {
      obj.flowRate = Math.round(message.flowRate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AngeliqueThermal>, I>>(base?: I): AngeliqueThermal {
    return AngeliqueThermal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AngeliqueThermal>, I>>(object: I): AngeliqueThermal {
    const message = createBaseAngeliqueThermal();
    message.cellsTemp = object.cellsTemp?.map((e) => e) || [];
    message.ambientTemp = object.ambientTemp ?? 0;
    message.inverterTemp = object.inverterTemp ?? 0;
    message.motorTemp = object.motorTemp ?? 0;
    message.waterMotorTemp = object.waterMotorTemp ?? 0;
    message.waterInverterTemp = object.waterInverterTemp ?? 0;
    message.waterRadTemp = object.waterRadTemp ?? 0;
    message.radFanSet = object.radFanSet ?? 0;
    message.radFanRpm = object.radFanRpm ?? 0;
    message.battFanSet = object.battFanSet ?? 0;
    message.battFanRpm = object.battFanRpm ?? 0;
    message.flowRate = object.flowRate ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
