{
 "title": "Orion Dynamics - Retrospective",
 "tags": [
  "orion",
  "retrospective",
  "dynamics"
 ],
 "time": { "from": "2026-03-11T00:23:00.000Z", "to": "2026-03-12T07:17:00.000Z" },
 "panels": [
  {
   "title": "Wheel Speeds [rad/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(flw_speed) AS \"usm/flw_speed [rad/s]\", AVG(frw_speed) AS \"usm/frw_speed [rad/s]\", AVG(blw_speed) AS \"usm/blw_speed [rad/s]\", AVG(brw_speed) AS \"usm/brw_speed [rad/s]\", AVG(wheel_speed) AS \"usm/wheel_speed [rad/s]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.flw_speed, dynamics.frw_speed, dynamics.blw_speed, dynamics.brw_speed, dynamics.wheel_speed\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ride Heights [mm]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(fl_ride_height) AS \"csm/fl_ride_height [mm]\", AVG(fr_ride_height) AS \"csm/fr_ride_height [mm]\", AVG(bl_ride_height) AS \"csm/bl_ride_height [mm]\", AVG(br_ride_height) AS \"csm/br_ride_height [mm]\", AVG(ride_height) AS \"usm/ride_height [mm]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.fl_ride_height, dynamics.fr_ride_height, dynamics.bl_ride_height, dynamics.br_ride_height, dynamics.ride_height\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Strain Gauges and Suspension Pots [V]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(fl_strain_gauge_v) AS \"csm/fl_strain_gauge_v [V]\", AVG(fr_strain_gauge_v) AS \"csm/fr_strain_gauge_v [V]\", AVG(bl_strain_gauge_v) AS \"csm/bl_strain_gauge_v [V]\", AVG(br_strain_gauge_v) AS \"csm/br_strain_gauge_v [V]\", AVG(fl_sus_pot_v) AS \"csm/fl_sus_pot_v [V]\", AVG(fr_sus_pot_v) AS \"csm/fr_sus_pot_v [V]\", AVG(bl_sus_pot_v) AS \"csm/bl_sus_pot_v [V]\", AVG(br_sus_pot_v) AS \"csm/br_sus_pot_v [V]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.fl_strain_gauge_v, dynamics.fr_strain_gauge_v, dynamics.bl_strain_gauge_v, dynamics.br_strain_gauge_v, dynamics.fl_sus_pot_v, dynamics.fr_sus_pot_v, dynamics.bl_sus_pot_v, dynamics.br_sus_pot_v\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Accelerator Pedal Travel [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(accel_pedal_travel) AS \"vcu/accel_pedal_travel [%]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.accel_pedal_travel\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Steering Angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(steer_col_angle) AS \"vcu/steer_col_angle [deg]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.steer_col_angle\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sprung Acceleration Components [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(fl_sprung_accel[1]) AS \"csm/fl_sprung_accel_x [m/s^2]\", AVG(fl_sprung_accel[2]) AS \"csm/fl_sprung_accel_y [m/s^2]\", AVG(fl_sprung_accel[3]) AS \"csm/fl_sprung_accel_z [m/s^2]\", AVG(fr_sprung_accel[1]) AS \"csm/fr_sprung_accel_x [m/s^2]\", AVG(fr_sprung_accel[2]) AS \"csm/fr_sprung_accel_y [m/s^2]\", AVG(fr_sprung_accel[3]) AS \"csm/fr_sprung_accel_z [m/s^2]\", AVG(bl_sprung_accel[1]) AS \"csm/bl_sprung_accel_x [m/s^2]\", AVG(bl_sprung_accel[2]) AS \"csm/bl_sprung_accel_y [m/s^2]\", AVG(bl_sprung_accel[3]) AS \"csm/bl_sprung_accel_z [m/s^2]\", AVG(br_sprung_accel[1]) AS \"csm/br_sprung_accel_x [m/s^2]\", AVG(br_sprung_accel[2]) AS \"csm/br_sprung_accel_y [m/s^2]\", AVG(br_sprung_accel[3]) AS \"csm/br_sprung_accel_z [m/s^2]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.fl_sprung_accel, dynamics.fr_sprung_accel, dynamics.bl_sprung_accel, dynamics.br_sprung_accel\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Unsprung Acceleration Components [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(ts, $__interval),\n    AVG(fl_unsprung_accel[1]) AS \"usm/fl_unsprung_accel_x [m/s^2]\", AVG(fl_unsprung_accel[2]) AS \"usm/fl_unsprung_accel_y [m/s^2]\", AVG(fl_unsprung_accel[3]) AS \"usm/fl_unsprung_accel_z [m/s^2]\", AVG(fr_unsprung_accel[1]) AS \"usm/fr_unsprung_accel_x [m/s^2]\", AVG(fr_unsprung_accel[2]) AS \"usm/fr_unsprung_accel_y [m/s^2]\", AVG(fr_unsprung_accel[3]) AS \"usm/fr_unsprung_accel_z [m/s^2]\", AVG(bl_unsprung_accel[1]) AS \"usm/bl_unsprung_accel_x [m/s^2]\", AVG(bl_unsprung_accel[2]) AS \"usm/bl_unsprung_accel_y [m/s^2]\", AVG(bl_unsprung_accel[3]) AS \"usm/bl_unsprung_accel_z [m/s^2]\", AVG(br_unsprung_accel[1]) AS \"usm/br_unsprung_accel_x [m/s^2]\", AVG(br_unsprung_accel[2]) AS \"usm/br_unsprung_accel_y [m/s^2]\", AVG(br_unsprung_accel[3]) AS \"usm/br_unsprung_accel_z [m/s^2]\"\nFROM (\n    SELECT\n        to_timestamp(packet.time / 1000.0) AS ts,\n        dynamics.fl_unsprung_accel, dynamics.fr_unsprung_accel, dynamics.bl_unsprung_accel, dynamics.br_unsprung_accel\n    FROM dynamics JOIN packet ON packet.packet_id = dynamics.packet_id\n) t\nWHERE $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}