[package]
name = "lhre-2026"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
socketcan = "3.0"
rumqttc = { version = "0.24", default-features = false }

[dev-dependencies]
prost-build = "0.12"
