load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "cand",
    srcs = ["main.rs"],
    deps = [
    ] + select({
        "@platforms//os:linux": [
            "@crates//:socketcan",
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)