load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "real",
    srcs = ["main.rs"],
    deps = [
        "@crate_index//:anyhow",
        "@crate_index//:clap",
        "@crate_index//:socketcan",
    ],
)

rust_binary(
    name = "fake",
    srcs = ["main.rs"],
    deps = [
        "@crate_index//:anyhow",
        "@crate_index//:clap",
    ],
)