{
 "title": "Orion Fault & Shutdown Status (Real-Time)",
 "tags": [
  "orion",
  "real-time",
  "use-case",
  "safety"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "HVC State Machine",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.hvc_state_machine FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS hvc_state_machine;"
    }
   ]
  },
  {
   "title": "PRNDL State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.prndl_state FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS prndl_state;"
    }
   ]
  },
  {
   "title": "Shutdown Current [A]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.shutdown_current FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -9999) AS shutdown_current;"
    }
   ]
  },
  {
   "title": "POST Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.post_faults FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -9999) AS post_faults;"
    }
   ]
  },
  {
   "title": "RUN Faults",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.run_faults FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -9999) AS run_faults;"
    }
   ]
  },
  {
   "title": "Shutdown Leg 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.shutdown_leg1::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS shutdown_leg1;"
    }
   ]
  },
  {
   "title": "Shutdown Leg 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.shutdown_leg2::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS shutdown_leg2;"
    }
   ]
  },
  {
   "title": "Shutdown Leg 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.shutdown_leg3::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS shutdown_leg3;"
    }
   ]
  },
  {
   "title": "Shutdown Leg 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.shutdown_leg4::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS shutdown_leg4;"
    }
   ]
  },
  {
   "title": "NEG HV Contactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.neg_hv_contactor::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS neg_hv_contactor;"
    }
   ]
  },
  {
   "title": "POS HV Contactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.pos_hv_contactor::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS pos_hv_contactor;"
    }
   ]
  },
  {
   "title": "Precharge Contactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.precharge_contactor::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS precharge_contactor;"
    }
   ]
  },
  {
   "title": "R2D Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.r2d_status::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS r2d_status;"
    }
   ]
  },
  {
   "title": "APPS Implausibility",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.apps_implause::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS apps_implause;"
    }
   ]
  },
  {
   "title": "APPS Mismatch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.apps_mismatch::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS apps_mismatch;"
    }
   ]
  },
  {
   "title": "BPPS Mismatch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bpps_mismatch::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bpps_mismatch;"
    }
   ]
  },
  {
   "title": "APPS1 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.apps1_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS apps1_disconnect;"
    }
   ]
  },
  {
   "title": "APPS2 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.apps2_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS apps2_disconnect;"
    }
   ]
  },
  {
   "title": "BPPS1 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bpps1_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bpps1_disconnect;"
    }
   ]
  },
  {
   "title": "BPPS2 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bpps2_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bpps2_disconnect;"
    }
   ]
  },
  {
   "title": "STOMP Fault",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.stomp_fault::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS stomp_fault;"
    }
   ]
  },
  {
   "title": "IMD Ground Isolation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.imd_gnd_isolation_error::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS imd_gnd_isolation_error;"
    }
   ]
  },
  {
   "title": "BMB Comm Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.bmb_comm_error::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bmb_comm_error;"
    }
   ]
  },
  {
   "title": "R2D Authorized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_low.r2d_authorized::int FROM diagnostics_low JOIN packet ON packet.packet_id = diagnostics_low.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS r2d_authorized;"
    }
   ]
  },
  {
   "title": "BSE1 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bse1_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bse1_disconnect;"
    }
   ]
  },
  {
   "title": "BSE2 Disconnect",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bse2_disconnect::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bse2_disconnect;"
    }
   ]
  },
  {
   "title": "BSE1 Out of Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.bse1_out_range::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS bse1_out_range;"
    }
   ]
  },
  {
   "title": "Boards Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.boards_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS boards_fuse;"
    }
   ]
  },
  {
   "title": "RTD Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.rtd_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS rtd_fuse;"
    }
   ]
  },
  {
   "title": "Shutdown Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.shtdn_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS shtdn_fuse;"
    }
   ]
  },
  {
   "title": "LL Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.ll_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS ll_fuse;"
    }
   ]
  },
  {
   "title": "Motor Pump Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.motor_pump_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS motor_pump_fuse;"
    }
   ]
  },
  {
   "title": "Batt Pump Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.batt_pump_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS batt_pump_fuse;"
    }
   ]
  },
  {
   "title": "Batt Fans Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.batt_fans_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS batt_fans_fuse;"
    }
   ]
  },
  {
   "title": "Brake Light Fuse",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT diagnostics_high.brake_light_fuse::int FROM diagnostics_high JOIN packet ON packet.packet_id = diagnostics_high.packet_id ORDER BY packet.time DESC LIMIT 1), -1) AS brake_light_fuse;"
    }
   ]
  }
 ]
}