<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lhr_gazebo</name>
  <version>0.0.0</version>
  <description>Gazebo simulation for FSAE driverless.</description>
  <maintainer email="gray@todo.todo">gray</maintainer>
  <license>TODO: License declaration</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_interfaces</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>ackermann_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>lhr_track_builder</exec_depend>
  <exec_depend>lhr_control</exec_depend>
  <exec_depend>lhr_metrics</exec_depend>
  <exec_depend>lhr_mission_manager</exec_depend>
  <exec_depend>lhr_trackgen</exec_depend>
  <exec_depend>lhr_sensor_sim</exec_depend>
  <exec_depend>lhr_perception</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
