load("@rules_rust//rust:defs.bzl", "rust_library")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")

package(default_visibility = ["//visibility:public"])

cargo_build_script(
    name = "sensor_proto_gen",
    srcs = ["build.rs"], # Move your build.rs here
    data = ["//drivers/proto:template.proto", "@protobuf//:protoc"],
    build_script_env = {
        "PROTO_FILE": "$(location //drivers/proto:template.proto)",
        "PROTOC": "$(execpath @protobuf//:protoc)",
    },
    deps = ["@crate_index//:prost-build"],
)