load("//tools:outputs/build_outputs.bzl", "firmware_project_g4")

firmware_project_g4(
    name = "pdu_firmware_2026",
    linker_script = "STM32G474VETx_FLASH.ld",
    startup_script = "startup_stm32g474xx.s",
    defines = [
        "STM32G474xx",
    ],
    extra_srcs = glob([
        "pdu/*.c",
        "pdu/*.h"
    ]),
    extra_includes = ["pdu/"],
    enable_freertos = True,
    enable_usb = True,
    usb_device_name = "Power Delivery Unit (PDU)",
    enable_dfu = True,
)
