{
 "title": "Dynamics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT gps[0] as lat, gps[1] as lon \r\n\r\nFROM dynamics \r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\n\r\nORDER BY packet.packet_id DESC\r\n\r\nLIMIT 4150\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "GPS Heading vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, dynamics.gps_heading\r\n\r\nFROM dynamics\r\n\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nORDER BY dynamics.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Lateral Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  packet.time,\r\n  dynamics.vcu_velocity[1] as lat_accel\r\nFROM dynamics\r\n\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "GPS Velocity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  packet.time,\r\n  dynamics.gps_velocity \r\nFROM dynamics\r\n\r\nJOIN packet ON packet.packet_id = dynamics.packet_id\r\nLIMIT 5000"
    }
   ]
  }
 ]
}