{
 "title": "High Voltage Battery",
 "time": { "from": "2025-02-27T06:22:49.959Z", "to": "2025-02-27T06:23:23.981Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Cell Voltages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT cells_v \r\n\r\nFROM diagnostics \r\n\r\nORDER BY packet_id DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "HV Power vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\npacket.time, \r\npack.hv_c * pack.hv_pack_v as hv_pack_power\r\n\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "High Voltage Battery Voltage vs Time ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, pack.hv_pack_v \r\n\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Charge State",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hv_charge_state\r\n\r\nFROM diagnostics\r\nORDER BY packet_id DESC \r\nLIMIT 1"
    }
   ]
  }
 ]
}