{
 "title": "Thermals Dashboard",
 "description": "- Battery\n- Cell temps\n- max\n- min\n- average\n- max temp delta\n- these metrics broken down per segment\n- visualization of each segment schematic with cell temps displayed corresponding to segment location\n- ACU\n- ambient temp\n- bus bar temps\n- precharge/discharge resistor temps\n- pack fuse temp?\n- Air / coolant loop\n- PWM / RPM / flowrate for any pumps\n- PWM / RPM for any fans\n- Inlet / outlet temp sense\n- thermal derate status\n- Motor / Inverter\n- PWM / RPM / flowrate for any pumps\n- PWM / RPM for any fans\n- Inlet / outlet temp\n- lamination thermistor\n- Inverter temp\n- thermal derate status\n- these metrics possibly displayed across thermal schematics / diagrams for easier visualization\n- valve states if that’s something designed",
 "time": { "from": "now-60s", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Ambient Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, thermal.ambient_temp \r\nFROM thermal\r\n\r\nJOIN packet ON packet.packet_id = thermal.packet_id\r\nORDER BY packet.packet_id DESC\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Water Cooling System Temperatures",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT water_motor_temp, water_inverter_temp, water_rad_temp FROM thermal "
    }
   ]
  },
  {
   "title": "Inverter Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, thermal.inverter_temp\r\nFROM thermal\r\nJOIN packet ON packet.packet_id = thermal.packet_id\r\nORDER BY packet.packet_id DESC\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, flow_rate\r\n\r\nFROM thermal \r\nJOIN packet ON packet.packet_id = thermal.packet_id\r\n\r\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Fan RPMs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rad_fan_rpm AS radiator_fan, batt_fan_rpm AS battery_fan\r\n\r\nFROM thermal\r\nORDER BY thermal.packet_id\r\nDESC LIMIT 1\r\n \r\n"
    }
   ]
  },
  {
   "title": "Cell Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cells_temp[1] AS section_1, cells_temp[2] AS section_2, cells_temp[3] AS section_3\r\nFROM thermal\r\n\r\nORDER BY packet_id\r\nDESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Average Cell Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT packet.time, pack.avg_cell_temp\r\nFROM pack\r\n\r\nJOIN packet ON packet.packet_id = pack.packet_id\r\nORDER BY packet.packet_id DESC\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Section 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nMIN(value) AS min_value,\r\nMAX(value) AS max_value,\r\n(MAX(value) - MIN(value))/2 AS avg_value,\r\nMAX(value) - MIN(value) AS max_delta\r\n\r\nFROM (\r\n    SELECT \r\n    packet_id, \r\n    UNNEST(cells_temp[1:28]) AS value\r\n    FROM thermal\r\n    ORDER BY packet_id DESC\r\n    \r\n) AS unnested\r\nGROUP BY packet_id\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Section 2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nMIN(value) AS min_value,\r\nMAX(value) AS max_value,\r\n(MAX(value) - MIN(value))/2 AS avg_value,\r\nMAX(value) - MIN(value) AS max_delta\r\n\r\nFROM (\r\n    SELECT \r\n    packet_id, \r\n    UNNEST(cells_temp[:56]) AS value\r\n    FROM thermal\r\n    ORDER BY packet_id DESC\r\n    \r\n) AS unnested\r\nGROUP BY packet_id\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n\r\n"
    }
   ]
  },
  {
   "title": "Section 4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nMIN(value) AS min_value,\r\nMAX(value) AS max_value,\r\n(MAX(value) - MIN(value))/2 AS avg_value,\r\nMAX(value) - MIN(value) AS max_delta\r\n\r\nFROM (\r\n    SELECT \r\n    packet_id, \r\n    UNNEST(cells_temp[85:112]) AS value\r\n    FROM thermal\r\n    ORDER BY packet_id DESC\r\n    \r\n) AS unnested\r\nGROUP BY packet_id\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Section 3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nMIN(value) AS min_value,\r\nMAX(value) AS max_value,\r\n(MAX(value) - MIN(value))/2 AS avg_value,\r\nMAX(value) - MIN(value) AS max_delta\r\n\r\nFROM (\r\n    SELECT \r\n    packet_id, \r\n    UNNEST(cells_temp[57:84]) AS value\r\n    FROM thermal\r\n    ORDER BY packet_id DESC\r\n    \r\n) AS unnested\r\nGROUP BY packet_id\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Section 5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nMIN(value) AS min_value,\r\nMAX(value) AS max_value,\r\n(MAX(value) - MIN(value))/2 AS avg_value,\r\nMAX(value) - MIN(value) AS max_delta\r\n\r\nFROM (\r\n    SELECT \r\n    packet_id, \r\n    UNNEST(cells_temp[112:141]) AS value\r\n    FROM thermal\r\n    ORDER BY packet_id DESC\r\n    \r\n) AS unnested\r\nGROUP BY packet_id\r\nORDER BY packet_id DESC\r\nLIMIT 1\r\n"
    }
   ]
  }
 ]
}