#ifndef UPDATE_PROTOCOL_H
#define UPDATE_PROTOCOL_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
  DEVICE_ID_ALL = 0,

  // Critical path
  DEVICE_ID_HVC,
  DEVICE_ID_VCU,
  DEVICE_ID_DUI,
  DEVICE_ID_PDU,
  DEVICE_ID_BEVO,

  // Non critical path
  DEVICE_ID_USM_FR,
  DEVICE_ID_USM_RR,
  DEVICE_ID_USM_FL,
  DEVICE_ID_USM_RL,
  DEVICE_ID_CSM_FR,
  DEVICE_ID_CSM_RR,
  DEVICE_ID_CSM_FL,
  DEVICE_ID_CSM_RL,
  DEVICE_ID_TSM,
} can_device_t;

typedef enum {
  UPDATE_COMMAND_WRITE,
  UPDATE_COMMAND_READ,
  UPDATE_COMMAND_ERASE,
  UPDATE_COMMAND_VERIFY,
  UPDATE_COMMAND_RESET,
  UPDATE_COMMAND_ABORT
} update_command_t;

typedef enum {
  UPDATE_RESPONSE_ACK,
  UPDATE_RESPONSE_NACK,
  UPDATE_RESPONSE_CRC_ERROR,
  UPDATE_RESPONSE_BUSY,
  UPDATE_RESPONSE_INVALID_ADDRESS,
  UPDATE_RESPONSE_INVALID_BLOCK_LENGTH,
  UPDATE_RESPONSE_INVALID_CRC,
  UPDATE_RESPONSE_INVALID_COMMAND,
  UPDATE_RESPONSE_INVALID_DEVICE_ID,
  UPDATE_RESPONSE_INVALID_PACKET_ID,
  UPDATE_RESPONSE_INVALID_PAYLOAD,
  UPDATE_RESPONSE_INVALID_RESPONSE,
  UPDATE_RESPONSE_INVALID_DATA,
} update_response_t;

#endif // UPDATE_PROTOCOL_H