syntax = "proto3";

message OrionSensorData {
    int64 time = 1;
    int64 packet_id = 2;
    Dynamics dynamics = 3;
    Controls controls = 4;
    Thermal thermal = 1002;
}

message Dynamics {
    float accelerator_pedal_travel = 1;
    float back_left_speed = 2;
    float back_left_suspension_potentiometer = 3;
    float back_right_suspension_potentiometer = 4;
    float bl_ride_height = 5;
    repeated float bl_sprung_accel = 6;
    float bl_strain_gauge_v = 7;
    repeated float bl_unsprung_accel = 8;
    float br_ride_height = 9;
    repeated float br_sprung_accel = 10;
    float br_strain_gauge_v = 11;
    repeated float br_unsprung_accel = 12;
    float brw_speed = 13;
    float fl_ride_height = 14;
    repeated float fl_sprung_accel = 15;
    float fl_strain_gauge_v = 16;
    repeated float fl_unsprung_accel = 17;
    float flw_speed = 18;
    float fr_ride_height = 19;
    repeated float fr_sprung_accel = 20;
    float fr_strain_gauge_v = 21;
    repeated float fr_unsprung_accel = 22;
    float front_left_suspension_potentiometer = 23;
    float front_right_suspension_potentiometer = 24;
    float frw_speed = 25;
    float steer_col_angle = 26;
}

message Controls {
    float apps1_travel = 1;
    float apps1_voltage = 2;
    float apps2_travel = 3;
    float apps2_voltage = 4;
    uint32 apps_faults = 5;
    float bpps1_travel = 6;
    float bpps1_voltage = 7;
    float bpps2_travel = 8;
    float bpps2_voltage = 9;
    uint32 bpps_faults = 10;
    float brake_bias = 11;
    float brake_pedal_travel = 12;
    float brake_pressure_f = 13;
    float brake_pressure_rall = 14;
    float brake_pressure_rbll = 15;
    float bse1_v = 16;
    float bse2_v = 17;
    float bse3_v = 18;
    uint32 bse_faults = 19;
}

message Thermal {
    float ambient_temp = 1;
    float batt_loop_batt_temp = 2;
    float batt_loop_rad_fan_speed = 3;
    float batt_loop_rad_temp = 4;
    float discharge_r_temp = 5;
    float inverter_temp = 6;
    float motor_temp = 7;
}
