class OrionPacket(BaseOrion):
    __tablename__ = 'packet'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, primary_key=True)
    time = Column(BigInteger, nullable=False)
    dynamics = relationship("OrionDynamics", uselist=False, back_populates="packet")
    controls = relationship("OrionControls", uselist=False, back_populates="packet")
    pack = relationship("OrionPack", uselist=False, back_populates="packet")
    diagnostics_high = relationship("OrionDiagnosticsHigh", uselist=False, back_populates="packet")
    diagnostics_low = relationship("OrionDiagnosticsLow", uselist=False, back_populates="packet")
    thermal = relationship("OrionThermal", uselist=False, back_populates="packet")
    board_status = relationship("OrionBoardStatus", uselist=False, back_populates="packet")

class OrionDynamics(BaseOrion):
    __tablename__ = 'dynamics'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    gps = Column(ARRAY(Float))
    gps_imu = Column(ARRAY(Float))
    gps_speed = Column(Float)
    bl_unsprung_accel = Column(ARRAY(Float))
    br_unsprung_accel = Column(ARRAY(Float))
    fl_unsprung_accel = Column(ARRAY(Float))
    fr_unsprung_accel = Column(ARRAY(Float))
    accel_pedal_travel = Column(Float)
    bl_wheel_speed = Column(Float)
    br_wheel_speed = Column(Float)
    fl_wheel_speed = Column(Float)
    fr_wheel_speed = Column(Float)
    steer_col_angle = Column(Float)
    bl_gyro = Column(ARRAY(Float))
    bl_sprung_accel = Column(ARRAY(Float))
    br_gyro = Column(ARRAY(Float))
    br_sprung_accel = Column(ARRAY(Float))
    fl_gyro = Column(ARRAY(Float))
    fl_sprung_accel = Column(ARRAY(Float))
    fr_gyro = Column(ARRAY(Float))
    fr_sprung_accel = Column(ARRAY(Float))
    bl_ride_height = Column(Float)
    bl_strain_gauge_v = Column(Float)
    bl_sus_pot_v = Column(Float)
    br_ride_height = Column(Float)
    br_strain_gauge_v = Column(Float)
    br_sus_pot_v = Column(Float)
    fl_ride_height = Column(Float)
    fl_strain_gauge_v = Column(Float)
    fl_sus_pot_v = Column(Float)
    fr_ride_height = Column(Float)
    fr_strain_gauge_v = Column(Float)
    fr_sus_pot_v = Column(Float)
    ride_height = Column(Float)
    wheel_speed = Column(Float)
    packet = relationship("OrionPacket", back_populates="dynamics")

class OrionControls(BaseOrion):
    __tablename__ = 'controls'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    motor_speed = Column(Float)
    torque_feedback = Column(Float)
    apps1_travel = Column(Float)
    apps1_v = Column(Float)
    apps2_travel = Column(Float)
    apps2_v = Column(Float)
    bpps1_travel = Column(Float)
    bpps1_v = Column(Float)
    bpps2_travel = Column(Float)
    bpps2_v = Column(Float)
    brake_bias = Column(Float)
    brake_light_pct = Column(Float)
    brake_pressure_f = Column(Float)
    brake_pressure_rall = Column(Float)
    brake_pressure_rbll = Column(Float)
    bse1_v = Column(Float)
    bse2_v = Column(Float)
    bse3_v = Column(Float)
    lights_current = Column(Float)
    rpm_request = Column(Float)
    torque_command = Column(Float)
    torque_limit = Column(Float)
    torque_request = Column(Float)
    commanded_torque = Column(Float)
    motor_angle = Column(Float)
    direction = Column(Boolean)
    enable = Column(Boolean)
    line_lock_enabled = Column(Boolean)
    torque_shudder = Column(Float)
    bse3 = Column(Float)
    event_mode = Column(Float)
    net_energy = Column(Float)
    regen_energy = Column(Float)
    torque_lookup = Column(Float)
    torque_derated = Column(Float)
    torque_power_limited = Column(Float)
    torque_traction_controlled = Column(Float)
    packet = relationship("OrionPacket", back_populates="controls")

class OrionPack(BaseOrion):
    __tablename__ = 'pack'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    bus_voltage = Column(Float)
    lv_boards_current = Column(Float)
    soc_estimate = Column(Float)
    cells_v = Column(ARRAY(Float))
    dc_bus_v = Column(Float)
    delta_resolver_angle = Column(Float)
    inverter_freq = Column(Float)
    neutral_output_v = Column(Float)
    time_since_on = Column(Float)
    vab_vq_v = Column(Float)
    vbc_vd_v = Column(Float)
    cells_temps = Column(ARRAY(Float))
    dc_bus_current = Column(Float)
    hv_c = Column(Float)
    hv_pack_v = Column(Float)
    hv_soc = Column(Float)
    lv_batt_c = Column(Float)
    lv_batt_t = Column(Float)
    lv_batt_v = Column(Float)
    phase_a_current = Column(Float)
    phase_b_current = Column(Float)
    phase_c_current = Column(Float)
    packet = relationship("OrionPacket", back_populates="pack")

class OrionDiagnosticsHigh(BaseOrion):
    __tablename__ = 'diagnostics_high'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    prndl_state = Column(Float)
    shutdown_current = Column(Float)
    hvc_state_machine = Column(Float)
    post_faults = Column(Float)
    run_faults = Column(Float)
    apps1_disconnect = Column(Boolean)
    apps1_out_range = Column(Boolean)
    apps2_disconnect = Column(Boolean)
    apps2_out_range = Column(Boolean)
    apps_implause = Column(Boolean)
    apps_mismatch = Column(Boolean)
    batt_fans_fuse = Column(Boolean)
    batt_pump_fuse = Column(Boolean)
    boards_fuse = Column(Boolean)
    bpps1_disconnect = Column(Boolean)
    bpps1_out_range = Column(Boolean)
    bpps2_disconnect = Column(Boolean)
    bpps2_out_range = Column(Boolean)
    bpps_mismatch = Column(Boolean)
    brake_light_fuse = Column(Boolean)
    bse1_disconnect = Column(Boolean)
    bse1_out_range = Column(Boolean)
    bse2_disconnect = Column(Boolean)
    bse2_out_range = Column(Boolean)
    ll_fuse = Column(Boolean)
    motor_pump_fuse = Column(Boolean)
    r2d_buzzer = Column(Boolean)
    rtd_fuse = Column(Boolean)
    shtdn_fuse = Column(Boolean)
    shutdown_bspd_status = Column(Boolean)
    shutdown_emeter_status = Column(Boolean)
    spare_fuse = Column(Boolean)
    stomp_fault = Column(Boolean)
    tssi_green_fuse = Column(Boolean)
    tssi_red_fuse = Column(Boolean)
    neg_hv_contactor = Column(Boolean)
    pos_hv_contactor = Column(Boolean)
    precharge_contactor = Column(Boolean)
    packet = relationship("OrionPacket", back_populates="diagnostics_high")

class OrionDiagnosticsLow(BaseOrion):
    __tablename__ = 'diagnostics_low'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    precharge_r_temp = Column(Float)
    bmb_comm_error = Column(Boolean)
    imd_gnd_isolation_error = Column(Boolean)
    r2d_authorized = Column(Boolean)
    r2d_status = Column(Boolean)
    shutdown_leg1 = Column(Boolean)
    shutdown_leg2 = Column(Boolean)
    shutdown_leg3 = Column(Boolean)
    shutdown_leg4 = Column(Boolean)
    temp_imd_1 = Column(Boolean)
    temp_imd_2 = Column(Boolean)
    temp_shutdown_1 = Column(Boolean)
    temp_shutdown_2 = Column(Boolean)
    charger_current = Column(Float)
    charger_voltage = Column(Float)
    charger_enabled = Column(Boolean)
    imd_led = Column(Boolean)
    packet = relationship("OrionPacket", back_populates="diagnostics_low")

class OrionThermal(BaseOrion):
    __tablename__ = 'thermal'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    batt_cooling_current = Column(Float)
    motor_cooling_current = Column(Float)
    ambient_temp = Column(Float)
    motor_temp = Column(Float)
    batt_loop_batt_temp = Column(Float)
    batt_loop_rad_fan_speed = Column(Float)
    batt_loop_rad_temp = Column(Float)
    battery_fan_rpm = Column(Float)
    bus_bar_temp1 = Column(Float)
    bus_bar_temp2 = Column(Float)
    bus_bar_temp3 = Column(Float)
    cell_bottom_temp = Column(Float)
    cell_top_temp = Column(Float)
    coolant_flow_lpm = Column(Float)
    coolant_temp = Column(Float)
    discharge_r_temp = Column(Float)
    fan_rpm = Column(Float)
    gate_driver_temp = Column(Float)
    inverter_hotspot_temp = Column(Float)
    inverter_temp = Column(Float)
    max_cell_voltage = Column(Float)
    min_cell_voltage = Column(Float)
    module_a_temp = Column(Float)
    module_b_temp = Column(Float)
    module_c_temp = Column(Float)
    motor_loop_inverter_temp = Column(Float)
    motor_loop_motor_temp = Column(Float)
    motor_loop_rad_temp = Column(Float)
    temp_ams_1 = Column(Boolean)
    temp_ams_2 = Column(Boolean)
    temp_command_1 = Column(Boolean)
    temp_command_2 = Column(Boolean)
    temp_output_1 = Column(Boolean)
    temp_output_2 = Column(Boolean)
    max_charge_current = Column(Float)
    max_charge_voltage = Column(Float)
    bms_led = Column(Boolean)
    charger_enable = Column(Boolean)
    packet = relationship("OrionPacket", back_populates="thermal")

class OrionBoardStatus(BaseOrion):
    __tablename__ = 'board_status'
    __table_args__ = {'schema': 'public', 'extend_existing': True}
    packet_id = Column(BigInteger, ForeignKey('public.packet.packet_id'), primary_key=True)
    csm_last_seen_s = Column(Float)
    dui_last_seen_s = Column(Float)
    hvc_last_seen_s = Column(Float)
    inverter_last_seen_s = Column(Float)
    pdu_last_seen_s = Column(Float)
    tsm_last_seen_s = Column(Float)
    usm_last_seen_s = Column(Float)
    vcu_last_seen_s = Column(Float)
    packet = relationship("OrionPacket", back_populates="board_status")
