# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x06\x62ridge\"6\n\x11SensorDataRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x10\n\x08\x63\x61r_type\x18\x02 \x01(\t\"6\n\x12SensorDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2X\n\rBridgeService\x12G\n\x0eSendSensorData\x12\x19.bridge.SensorDataRequest\x1a\x1a.bridge.SensorDataResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_SENSORDATAREQUEST']._serialized_start=24
  _globals['_SENSORDATAREQUEST']._serialized_end=78
  _globals['_SENSORDATARESPONSE']._serialized_start=80
  _globals['_SENSORDATARESPONSE']._serialized_end=134
  _globals['_BRIDGESERVICE']._serialized_start=136
  _globals['_BRIDGESERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
