name: presubmit
run-name: Presubmit run triggered by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  bazel-build-test:
    name: Bazel Presubmit Checks
    runs-on: ubuntu-22.04
    # Define environment variables from secrets at the job level
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      ELECTRIC_PWD: ${{ secrets.ELECTRIC_PWD }}
      GRAFANA_PWD: ${{ secrets.GRAFANA_PWD }}
      ANALYSIS_PWD: ${{ secrets.ANALYSIS_PWD }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      AUTH_DATABASE_URL: ${{ secrets.AUTH_DATABASE_URL }}
      KAFKA_BROKERS: ${{ secrets.KAFKA_BROKERS }}
      KAFKA_CLIENT_ID: ${{ secrets.KAFKA_CLIENT_ID }}
      KAFKA_GROUP_ID: ${{ secrets.KAFKA_GROUP_ID }}
      KAFKA_TOPICS: ${{ secrets.KAFKA_TOPICS }}
      KAFKA_AUTO_CREATE: ${{ secrets.KAFKA_AUTO_CREATE }}
      KAFKA_ROUTES_FILE: ${{ secrets.KAFKA_ROUTES_FILE }}
    steps:
      # - name: Install build dependencies
      #   run: sudo apt-get update && sudo apt-get install libtinfo5
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Get Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Build All
        run: bazel build //... --config=ci
      - name: Test All
        # Pass all telemtry-related env vars to Bazel test sandbox
        run: |
          bazel test //... --test_output=errors --config=ci \
            --test_env=POSTGRES_USER \
            --test_env=POSTGRES_DB \
            --test_env=POSTGRES_PASSWORD \
            --test_env=POSTGRES_HOST \
            --test_env=POSTGRES_PORT \
            --test_env=ELECTRIC_PWD \
            --test_env=GRAFANA_PWD \
            --test_env=ANALYSIS_PWD \
            --test_env=NEXTAUTH_SECRET \
            --test_env=AUTH_DATABASE_URL \
            --test_env=KAFKA_BROKERS \
            --test_env=KAFKA_CLIENT_ID \
            --test_env=KAFKA_GROUP_ID \
            --test_env=KAFKA_TOPICS \
            --test_env=KAFKA_AUTO_CREATE \
            --test_env=KAFKA_ROUTES_FILE
