# telemtry/analysis/tests/BUILD.bazel

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "analysis_tests",
    srcs = ["sample_analysis_test.py"],
    deps = [
        "//telemtry/analysis:analysis_lib",
    ],
    main = "sample_analysis_test.py",
    tags = ["manual"],
    target_compatible_with = ["@platforms//os:linux"],
)
